import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*<h1 className={styles.title}>neighbor-ryan.org</h1>*/}

        <div className="logo">
          <Image src="/imgs/bpt.png"
                 alt="Bike against railing at Brookfield Place ferry terminal, Jersey City skyline in background"
                 width={800} height={600}
          />
        </div>
        <hr></hr>
        <div className="posts">
          <h2>Posts</h2>
          <h3><a href="https://bikejc.github.io/maps">Jersey City Protected Bike Lane + Ward Map</a></h3>
          <h3><a href="https://ctbk.dev">ctbk.dev</a>: Citi Bike Dashboard</h3>
          <h3><a href="https://ebikes.neighbor-ryan.org">E-Bikes Are a Transportation Revolution</a></h3>
          <h3><a href="https://neighbor-ryan.org/turnpiketrap">E-Bikes Are a Transportation Revolution</a></h3>
          <h3><a href="https://bikejc.github.io/bike-master-plan">Jersey City Protected Bike Lane + Ward Map</a></h3>
        </div>
        <hr />
        <div className="socials">
          <p>
            <a className="icon" href="https://twitter.com/runsascoded" title="Neighbor Ryan on Twitter">
              <img src="/imgs/twitter.png" width="30" height="30" alt="Twitter logo"/>
            </a>
            <a className="icon" href="https://www.youtube.com/@neighborryan" title="Neighbor Ryan on YouTube">
              <img src="/imgs/youtube.png" width="30" height="30" alt="YouTube logo"/>
            </a>
            <a className="icon" href="https://github.com/neighbor-ryan" title="Neighbor Ryan on GitHub">
              <img src="/imgs/github.png" width="30" height="30" alt="GitHub logo"/>
            </a>
            <a className="icon" href="https://instagram.com/neighbor_ryan" title="Neighbor Ryan on Instagram">
              <img src="/imgs/insta.png" width="30" height="30" alt="Instagram logo"/>
            </a>
          </p>
        </div>
      </main>
    </div>
  )
}

export default Home
