name: Build + Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Build + Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: yarn.lock
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: npm run gha-export
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
